# Generated by Django 6.1.1 on 2026-09-28 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0002_song_language_song_number_song_original_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageitem',
            name='file_soft',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='imageitem',
            name='file_strong',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='imageitem',
            name='file_thumb',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='imageitem',
            name='fit',
            field=models.CharField(blank=True, default='blur', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='imageitem',
            name='sha256',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
